config/routes.rb
Rails.application.routes.draw do
  root "rates#index"
  
  resources :rates

  namespace :admin do
    resources :rates
  end

end

app/models/currency.rb
class Currency < ActiveRecord::Base
	validates :iso, :country, :buy_price, :sell_price, presence: true
	validates :iso, :country, uniqueness: true
end

app/controllers/admin/rates_controller.rb
class Admin::RatesController < ApplicationController
  def index
  	@rates = Currency.all
  end

  def new
  	@rate = Currency.new
  end

  def create
  	@rate = Currency.new(currency_params)
  	if @rate.save
  		redirect_to admin_rates_path, notice: "#{@rate.country} successfully created."
  	else
  		render :new
  	end
  end

  def edit
  	@rate = Currency.find(params[:id])
  end

  def update
  	@rate = Currency.find(params[:id])
  	if @rate.update(currency_params)
  		redirect_to admin_rates_path, notice: "#{@rate.country} successfully updated."
  	else
  		render :edit
  	end
  end

  def destroy
  	@rate = Currency.find(params[:id]).destroy
  	redirect_to admin_rates_path, notice: "#{@rate.country} successfully removed."
  end

  private

  def currency_params
  	params.require(:currency).permit!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/rates_controller.rb
class RatesController < ApplicationController
  def index
  	if params[:search]
  		@rates = Currency.where("iso ilike ?", "%#{params[:search]}%")
  	else
  		@rates = Currency.order("ISO asc")
  	end
  end
end

app/helpers/admin/rates_helper.rb
module Admin::RatesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rates_helper.rb
module RatesHelper
end

app/views/admin/rates/_form.html.erb
<%= f.input :iso %>
<%= f.input :country, as: :string %>
<%= f.input :buy_price %>
<%= f.input :sell_price %>
<%= f.button :submit %>

app/views/admin/rates/edit.html.erb
<div class="row">
	<div class="large-6 columns">
		<%= simple_form_for @rate, url: admin_rate_path, method: :patch do |f| %>
			<%= render "form", f: f %>
		<% end %>
	</div>
</div>

app/views/admin/rates/index.html.erb
<table class="large-12">
  <thead>
    <tr>
      <th>ISO</th>
      <th>Country</th>
      <th>Buy Price</th>
      <th>Sell Price</th>
      <th><%= link_to "Create New Rate", new_admin_rate_path %></th>
    </tr>
  </thead>
  <tbody>
  	<% @rates.each do |r| %>
	    <tr>
	      <td><%= r.iso %></td>
	      <td><%= r.country %></td>
	      <td><%= number_with_precision r.buy_price, precision: 3 %></td>	      
	      <td><%= number_with_precision r.sell_price, precision: 3 %></td>
	      <td>
	      	<%= link_to "Edit", edit_admin_rate_path(r) %>
	      	<%= link_to "Delete", admin_rate_path(r), method: :delete, data: { confirm: "Are you sure you want to remove #{r.country} rate?" } %>
	      </td>
	    </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/rates/new.html.erb
<div class="row">
	<div class="large-6 columns">
		<%= simple_form_for @rate, url: admin_rates_path do |f| %>
			<%= render "form", f: f %>
		<% end %>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "VBCE Rates" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <% if flash.notice %>
    <div data-alert class="alert-box success">
      <div class="row">
        <div class="large-12 columns">
          <%= flash.notice %>
        </div>
      </div>
      <a href="#" class="close">&times;</a>
    </div>
    <% end %>

    <% if flash.alert %>
    <div data-alert class="alert-box alert">
      <div class="row">
        <div class="large-12 columns">
          <%= flash.alert %>
        </div>
      </div>
      <a href="#" class="close">&times;</a>
    </div>
    <% end %>
    
    <div class="row">
      <div class="large-12 columns">
        <ul class="nav inline-list">
          <li><%= link_to "#{image_tag 'vbce-logo.gif'}".html_safe, root_path, class: "logo" %></li>
          <li><%= link_to "Rates", rates_path %></li>
          <li><%= link_to "Admin", admin_rates_path %></li>
        </ul>
      </div>
    </div>
    <div class="row">
      <div class="large-12 columns">
        <%= yield %>
      </div>
    </div> 
  </body>
</html>

app/views/rates/index.html.erb
<%= form_tag rates_path, method: :get do %>
  <%= text_field_tag :search, nil, placeholder: "Search... Enter ISO" %>
<% end %>

<table class="large-12">
  <thead>
    <tr>
      <th>ISO</th>
      <th>Country</th>
      <th>Buy Price</th>
      <th>Sell Price</th>      
    </tr>
  </thead>
  <tbody>
  	<% @rates.each do |r| %>
	    <tr>
	      <td><%= r.iso %></td>
	      <td><%= r.country %></td>
	      <td><%= number_with_precision r.buy_price, precision: 3 %></td>	      
	      <td><%= number_with_precision r.sell_price, precision: 3 %></td>	      
	    </tr>
    <% end %>
  </tbody>
</table>


<% if params[:search].present? %>
  <div class="text-center"><%= link_to "Clear Results", root_path %></div>
<% end %>